// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
	"github.com/Xia-Jialin/Go-000/Week04/user/dao"
	"github.com/Xia-Jialin/Go-000/Week04/user/service"
	"github.com/Xia-Jialin/Go-000/Week04/user/transport"
	"net/http"
)

// Injectors from wire.go:

func InitHttpHandler(userDAO dao.UserDAO, ctx context.Context) http.Handler {
	userService := service.MakeUserServiceImpl(userDAO)
	userEndpoints := NewUserEndpoints(userService)
	handler := transport.MakeHttpHandler(ctx, userEndpoints)
	return handler
}
