// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

import (
	"context"
<<<<<<< HEAD
	"github.com/Xia-Jialin/Go-000/Week04/user/dao"
	"github.com/Xia-Jialin/Go-000/Week04/user/service"
	"github.com/Xia-Jialin/Go-000/Week04/user/transport"
=======
	"github.com/cty898/Go-000/Week04/user/dao"
	"github.com/cty898/Go-000/Week04/user/service"
	"github.com/cty898/Go-000/Week04/user/transport"
>>>>>>> ee315abcb790869e30fe090de1f8ea2ef5d6413e
	"net/http"
)

// Injectors from wire.go:

func InitHttpHandler(userDAO dao.UserDAO, ctx context.Context) http.Handler {
	userService := service.MakeUserServiceImpl(userDAO)
	userEndpoints := NewUserEndpoints(userService)
	handler := transport.MakeHttpHandler(ctx, userEndpoints)
	return handler
}
